//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSpace.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogCategory
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public int BlogCategoryId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Category Category { get; set; }
    }
}
